[package]
name = "janvas_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.66"
web-sys = { version="0.3.60", features=["console", "CanvasRenderingContext2d"] }
console_error_panic_hook = { version = "0.1.1" }
wasm-bindgen = "0.2.89"
